---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
#This will fail if the target OS is not Ubuntu 14.04  
  - name: Fail if OS distro is not Ubuntu 14.04
    fail: msg="The role is designed only for Ubuntu 14.04"
    when: "{{ ansible_distribution_version | version_compare('14.04', '!=') }}"
#This task will install Python Pre-Requisites
  - name: Install Python Pre-Requisites
    apt: 
      name={{ item }} 
      state=present
    with_items:
      - python-dev
      - python-setuptools
#This task installs python pip
  - name: Install pip
    easy_install: 
      name=pip 
#This task installs docker-py package to interact with Ansible Docker module
  - name: Install docker-py
    pip: 
      name=docker-py 
      state=present
      version=1.1.0
#This Task add Docker Repository to apt
  - name: Add docker apt repo
    apt_repository:
      repo='deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
      state=present
#This Task imports gpg key 
  - name: Import the Docker repository key
    apt_key:
      url=https://apt.dockerproject.org/gpg
      state=present
      #id=2C52609D
#This task install Docker Software
  - name: Install Docker package
    apt:
      name=docker-engine
      update_cache=yes
#This task adds docker group 
  - name: Create a docker group
    group: 
      name=docker 
      state=present
#Adds users defined to docker group
  - name: Add user(s) to docker group
    user: 
      name={{ item }} 
      group=docker 
      state=present
    with_items: docker_users
    when: docker_users is defined

  - name: Ensures guacsql dir exists
    file: path=/opt/guacsql state=directory mode=0755

###################
#Task to pull Docker images
##################
  - name: Pull and Create the docker container glyptodon/guacd
    docker: 
      name: lab-guacd
      image: glyptodon/guacd
      state: started  

  - name: Pull and Create the docker container mysql
    docker: 
      name: lab-mysql
      image: mysql
      state: started
      env: "MYSQL_ROOT_PASSWORD=Random123"
      volumes:
        - /opt/guacsql:/var/lib/mysql

  - name: Wait a few minutes for the IPs to be set to the container
    wait_for: timeout=120

  - name: Get Docker logs for mysql
    action: command docker logs lab-mysql
    register: mysql_status

  - name: Print guacamole logs
    debug: msg={{ mysql_status.stdout }}    

  - name: copy initdb.sql to mysql container
    copy: src=./initdb.sql dest=/opt/guacsql owner=root group=docker mode=0644    

  - name: Importing initdb.sql to mysql docker container
    shell: docker exec -it lab-mysql bash -c 'mysql -uroot -p$MYSQL_ROOT_PASSWORD < /var/lib/mysql/initdb.sql'
    register: db_create_status

  - name: printing the mysql db creation status
    debug: msg={{ db_create_status.stdout }}

  - name: Pull and Create docker container glyptodon/guacamole
    docker:
      name: lab-guacamole
      image: glyptodon/guacamole
      state: started
      links:
      - "lab-guacd:guacd"
      - "lab-mysql:mysql"
      ports:
      - "80:8080"
      env:
          MYSQL_DATABASE=guacamole_db
          MYSQL_USER=guacamole_user
          MYSQL_PASSWORD=p4rER9hN2rvChApU

  - name: Get Docker logs for guacamole
    action: command docker logs lab-guacamole
    register: guacamole_status

  - name: Print guacamole logs
    debug: msg={{ guacamole_status.stdout }}








     