---
- hosts: all
  sudo: true
  tasks:
#This will fail if the target OS is not Ubuntu 14.04  
  - name: Fail if OS distro is not Ubuntu 14.04
    fail: msg="The role is designed only for Ubuntu 14.04"
    when: "{{ ansible_distribution_version | version_compare('14.04', '!=') }}"
#This task will install Python Pre-Requisites
  - name: Install Python Pre-Requisites
    apt: 
      name={{ item }} 
      state=present
    with_items:
      - python-dev
      - python-setuptools
#This task installs python pip
  - name: Install pip
    easy_install: 
      name=pip 
#This task installs docker-py package to interact with Ansible Docker module
  - name: Install docker-py
    pip: 
      name=docker-py 
      state=present
      version=1.1.0
#This Task add Docker Repository to apt
  - name: Add docker apt repo
    apt_repository:
      repo='deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
      state=present
#This Task imports gpg key 
  - name: Import the Docker repository key
    apt_key:
      url=https://apt.dockerproject.org/gpg
      state=present
      #id=2C52609D
#This task install Docker Software
  - name: Install Docker package
    apt:
      name=docker-engine
      update_cache=yes
#This task adds docker group 
  - name: Create a docker group
    group: 
      name=docker 
      state=present
#Adds users defined to docker group
  - name: Add user(s) to docker group
    user: 
      name={{ item }} 
      group=docker 
      state=present
    with_items: docker_users
    when: docker_users is defined

  - name: Ensures guacsql dir exists
    file: path=opt/guacsql state=directory mode=0755

###################
#Task to pull Docker images
##################
  - name: Pull and Create the docker container glyptodon/guacd
    docker: 
      name: lab-guacd
      image: glyptodon/guacd
      state: started

  - name: Pull and Create the docker container mysql
    docker: 
      name: lab-mysql
      image: mysql
      state: present
      env: "MYSQL_ROOT_PASSWORD=Random123"
      volumes:
      - /opt/guacsql:/var/lib/mysql


  - name: copy initdb.sql to mysql container
    copy: src=./initdb.sql dest=/opt/guacsql owner=root group=docker mode=0644


  - name: Start the mysql docker container
    docker:
      name: lab-mysql
      state: started



     